version: '3.8'

services:
  smartbed-mqtt:
    container_name: smartbed-mqtt
    image: dasutin/smartbed-mqtt:1.1.23
    restart: unless-stopped
    volumes:
      - ./data:/data
    depends_on:
      - mqtt
