version: '3.8'

services:
  smartbed-mqtt:
    container_name: smartbed-mqtt
    image: dasutin/smartbed-mqtt:1.1.23
    restart: unless-stopped
    network_mode: "host"
    environment:
      MQTT_HOST: ""
      MQTT_PORT: ""
      MQTT_USER: ""
      MQTT_PASSWORD: ""
      TYPE: ""
      SLEEPTRACKER_REFRESH_FREQUENCY: "1"
      SLEEPTRACKER_CREDENTIALS: |
        [
          {
            "email": "me@example.org",
            "password": "some strong password",
            "type": "tempur"
          }
        ]
      ERGOWIFI_CREDENTIALS: |
        [
          {
            "email": "me@example.org",
            "password": "some strong password"
          }
        ]
      ERGOMOTION_DEVICES: |
        [
          {
            "friendlyName": "ErgoMotion Bed",
            "ipAddress": "192.168.0.127",
            "remoteStyle": "M"
          }
        ]
      LOGICDATA_DEVICES: |
        [
          {
            "name": "WIND123456",
            "friendlyName": "Logicdata Bed"
          }
        ]
      BLE_PROXIES: |
        [
          {
            "host": "bluetooth-proxy.local"
          }
        ]
      RICHMAT_DEVICES: |
        [
          {
            "name": "QRRM12345",
            "friendlyName": "Richmat Bed",
            "remoteCode": "VIRM",
            "stayConnected": "false"
          }
        ]
      LINAK_DEVICES: |
        [
          {
            "name": "LINAK Bed 0123",
            "friendlyName": "Linak Bed",
            "hasMassage": true,
            "motorCount": 2
          }
        ]
      SOLACE_DEVICES: |
        [
          {
            "name": "S4-Y-123-456789",
            "friendlyName": "Solace Bed"
          }
        ]
      MOTOSLEEP_DEVICES: |
        [
          {
            "name": "HHC123ABCD",
            "friendlyName": "MotoSleep Bed"
          }
        ]
      REVERIE_DEVICES: |
        [
          {
            "name": "RPLC",
            "friendlyName": "Reverie Bed"
          }
        ]
      LEGGETTPLATT_DEVICES: |
        [
          {
            "name": "Smart Bed",
            "friendlyName": "Leggett Platt Bed"
          }
        ]
      OKIMAT_DEVICES: |
        [
          {
            "name": "OKIN_345678",
            "friendlyName": "Okimat Bed",
            "remoteCode": "94238"
          }
        ]
      KEESON_DEVICES: |
        [
          {
            "name": "KSBT03C000015046",
            "friendlyName": "Keeson Bed"
          }
        ]
      OCTO_DEVICES: |
        [
          {
            "name": "RC2",
            "friendlyName": "Octo Bed",
            "pin": "1234"
          }
        ]
      SCANNER_DEVICES: "[]"
    volumes:
      - ./data/options.json:/data/options.json
    depends_on:
      - mqtt
    labels:
      com.homeassistant.description: "A Home Assistant add-on to enable controlling smart beds."
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1883"]
      interval: 30s
      timeout: 10s
      retries: 3
